# Generated by Django 4.1.8 on 2024-02-27 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user_dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='emplist_dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPNO', models.CharField(max_length=10)),
                ('NAME_KO', models.CharField(max_length=100)),
                ('NAME_EN', models.CharField(max_length=100)),
                ('CLNM', models.CharField(blank=True, max_length=100)),
                ('CO_NM', models.CharField(max_length=100)),
                ('TEAM_NM', models.CharField(max_length=100)),
                ('PART_NM', models.CharField(max_length=100)),
                ('BU_NM', models.CharField(max_length=100)),
                ('EMAIL', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='filemanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('taskname', models.CharField(max_length=26)),
                ('file', models.FileField(blank=True, upload_to='file/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='login_log_dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('request_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='master_setting_dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('contents', models.CharField(max_length=20)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('empno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='task_comments_dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpa_id', models.CharField(max_length=10)),
                ('comment_id', models.CharField(max_length=21)),
                ('comment', models.CharField(max_length=100)),
                ('NAME_KO', models.CharField(blank=True, max_length=100)),
                ('PART_NM', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('use_yn', models.CharField(max_length=100)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('empno', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='task_info_detail_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('rpa_id', models.CharField(max_length=30)),
                ('rpamanager_chk', models.CharField(max_length=2)),
                ('analyze_date', models.CharField(max_length=10)),
                ('task_completed', models.CharField(max_length=2)),
                ('progress_job', models.TextField(blank=True)),
                ('progress_job_done', models.CharField(max_length=100)),
                ('retry_method', models.TextField(blank=True)),
                ('retry_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='task_info_dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('taskname', models.CharField(max_length=26)),
                ('taskexplanation', models.TextField(blank=True)),
                ('manager_name', models.TextField(blank=True)),
                ('manager_empno', models.TextField(blank=True)),
                ('rpa_method', models.CharField(max_length=100)),
                ('pertime_min', models.CharField(max_length=100)),
                ('task_group1', models.CharField(max_length=1000)),
                ('task_group2', models.CharField(max_length=1000)),
                ('progress_status', models.CharField(max_length=100)),
                ('use_yn', models.CharField(max_length=1)),
                ('manager_amount', models.CharField(max_length=10)),
                ('business_type', models.CharField(max_length=10)),
                ('change_reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='task_maillist_dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpa_id', models.CharField(max_length=10)),
                ('mailto', models.TextField(blank=True)),
                ('mailcc', models.TextField(blank=True)),
                ('EMPNO', models.CharField(max_length=10)),
                ('NAME_KO', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_log_dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpa_id', models.CharField(max_length=10)),
                ('change_log', models.TextField(blank=True)),
                ('empno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
